# Generated by Django 5.1.15 on 2026-03-11 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="duration_type",
            field=models.CharField(
                choices=[("month", "Monthly"), ("year", "Yearly")],
                default="month",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="washes_per_month",
            field=models.IntegerField(default=30),
        ),
    ]
