# Generated by Django 5.1.15 on 2026-03-11 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_plan_created_at_plan_duration_type_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="washes_per_month",
        ),
        migrations.AddField(
            model_name="plan",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="vendors.vendor",
            ),
            preserve_default=False,
        ),
    ]
