# Generated by Django 5.1.15 on 2026-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_remove_plan_washes_per_month_plan_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="vehicle_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vehicle Number"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="vehicle_number_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vehicle Number Updated At"
            ),
        ),
    ]
