# Generated by Django 5.1.15 on 2026-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Full Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                ],
                default="en",
                max_length=10,
                verbose_name="Preferred Language",
            ),
        ),
    ]
