# Generated by Django 5.1.15 on 2026-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_user_name_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plain_password_hint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stores plain password only when admin sets/resets it. Empty for user-created passwords.",
                max_length=128,
                verbose_name="Plain Password Hint (Admin)",
            ),
        ),
    ]
