# Generated by Django 5.1.15 on 2026-03-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="registration_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="registration_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="registration_code_used",
            field=models.BooleanField(default=False),
        ),
    ]
