# Generated by Django 5.1.15 on 2026-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_registration_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="map_visible",
            field=models.BooleanField(
                default=True,
                help_text="If False, this center will NOT appear on the customer-facing nearby centers map.",
                verbose_name="Visible on Customer Map",
            ),
        ),
    ]
